### ISSUE TITLE
Android 13 - Crashes on start

### ISSUE THREAD

**Issue by TimoGoetze** [mcastillof/FakeTraveler#56]
**Describe the bug**

**Information:**
 - OS: [e.g. Android 7.0] Stacktrace from Android 13 (GrapeheneOS on Pixel6) 2022.08.30 - same Crash on Stock android
 - FakeTraveler version: [e.g. 1.6]

**To Reproduce**
1. Go to '...' Choose location and press start. then it crashes.

**Expected behavior**

works and doesnt crash

```
type: crash
osVersion: google/oriole/oriole:13/TP1A.220624.021/2022083000:user/release-keys
package: cl.coders.faketraveler:7
process: cl.coders.faketraveler

java.lang.IllegalStateException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:2996)
	at android.os.Parcel.readException(Parcel.java:2979)
	at android.os.Parcel.readException(Parcel.java:2921)
	at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:2154)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2113)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2088)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2062)
	at cl.coders.faketraveler.MockLocationProvider.<init>(MockLocationProvider.java:28)
	at cl.coders.faketraveler.MainActivity.applyLocation(MainActivity.java:257)
	at cl.coders.faketraveler.MainActivity$1.onClick(MainActivity.java:81)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:200)
	at com.android.server.location.LocationManagerService.addLocationProviderManager(LocationManagerService.java:350)
	at com.android.server.location.LocationManagerService.getOrAddLocationProviderManager(LocationManagerService.java:342)
	at com.android.server.location.LocationManagerService.addTestProvider(LocationManagerService.java:1314)


```

**Screenshots**

**Logcat**
If the app is crashing, a logcat of the error could be very helpful. 

**Additional context**

**Comment by steel-steven-87** [comment]
Can confirm this stopped working for me after upgrading to Android 13.

**Comment by mzun1** [comment]
type: crash
osVersion: google/oriole/oriole:13/TP1A.220624.021/2022083000:user/release-keys
package: cl.coders.faketraveler:7
process: cl.coders.faketraveler

java.lang.IllegalStateException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:2996)
	at android.os.Parcel.readException(Parcel.java:2979)
	at android.os.Parcel.readException(Parcel.java:2921)
	at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:2154)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2113)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2088)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2062)
	at cl.coders.faketraveler.MockLocationProvider.<init>(MockLocationProvider.java:28)
	at cl.coders.faketraveler.MainActivity.applyLocation(MainActivity.java:257)
	at cl.coders.faketraveler.MainActivity$1.onClick(MainActivity.java:81)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29335)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:200)
	at com.android.server.location.LocationManagerService.addLocationProviderManager(LocationManagerService.java:350)
	at com.android.server.location.LocationManagerService.getOrAddLocationProviderManager(LocationManagerService.java:342)
	at com.android.server.location

**Comment by schklom** [comment]
FYI, a similar issue got fixed at https://github.com/warren-bank/Android-Mock-Location/issues/14 for my Pixel 6a with GrapheneOS.
The code workaround is dumb, but it works for me.
Maybe it works here too?

**Comment by warren-bank** [comment]
Hi, all. To quickly summarize the "dumb" workaround (as it's now affectionately known) mentioned by @schklom ...

* [this line of code](https://github.com/mcastillof/FakeTraveler/blob/v1.9.1/app/src/main/java/cl/coders/faketraveler/MockLocationProvider.java#L28) can.. on some devices (ie: Pixel 6+).. throw an _IllegalStateException_
* our fairly "dumb" workaround is to catch this exception and try again.. for [example](https://github.com/warren-bank/Android-Mock-Location/commit/225f74b2843a67685ac38a26fb53aa8fd45afaa9)

Also, I should probably mention..
with regard to the question of __why__ an _IllegalStateException_ is being thrown..
Daniel Micay, the founder and lead developer of GrapheneOS, offered a bit of a warning..
though not an explanation, he did say that he doesn't believe this is limited to the Pixel..
that there's nothing special about its hardware to cause this..
but rather, that it happens to be one of only a few devices that runs bleeding-edge AOSP code..
and in time, once device makers catch up, and update the version of Android 13 that's running on their products..
this issue will (most likely) be far more common.

**Comment by mcastillof** [comment]
@TimoGoetze I have made the change that @warren-bank is proposing. Can you test if [this APK](https://c.coders.cl/s/8WfcoxB3MLBcKLa) is working for you?

**Comment by warren-bank** [comment]
@mcastillof I'd offer to test your build myself, but I'm in the same boat. I don't have a device new enough to reproduce or test this bug. Consequently, I'm also not sure what the effect of this workaround actually is. It's either:
1. try once.. fail. try again.. succeed
2. foreach of N retry attempts: try.. fail. silently ignore particular location provider.

**Comment by mcastillof** [comment]
@warren-bank I wonder if a Pixel 6 device with Android 13 (arm64-v8a or x86) emulated using Android Studio could be useful to test the behavior.

**Comment by warren-bank** [comment]
I don't know.
Also, and this is just a personal quirk.. with a dash of laziness sprinkled on top, but I only test on a few real devices.
That said, it worked fine on a Galaxy S5 w/ LineageOS 20 (Android 13.0).
I was actually wondering whether [android-x86](https://www.android-x86.org/releases.html) had a nighly release to test in VirtualBox,
but the project looks like it might be dead?

**Comment by mcastillof** [comment]
I went ahead and tried a Pixel 6 pro with Android 13 (arm64-v8a) in Android Emulator within Android Studio. My host machine has an x86_64 architecture.

```
./emulator @Pixel_6_Pro_API_33
INFO    | Android emulator version 32.1.12.0 (build_id 9751036) (CL:N/A)
INFO    | Found systemPath /home/dodo/workspace/android/Android/Sdk/system-images/android-33/google_apis/arm64-v8a/
PANIC: Avd's CPU Architecture 'arm64' is not supported by the QEMU2 emulator on x86_64 host.

```

So, I will try try an x86_64 image now. Hope it works this time.

**Comment by warren-bank** [comment]
Yeah, definitely let me know the outcome. The x86_64 image will run.. dunno whether the bug will occur. Curious to find out.

I'm actually reading [this](https://stackoverflow.com/questions/25381991/running-android-emulator-using-nexus-5-factory-image).. and am tempted to try the same methodology to run the newest [Pixel factory image](https://developer.android.com/about/versions/13/download).. which we know is problematic.

**Comment by mcastillof** [comment]
Now I'm a bit confused. I only use  LineageOS, and I don't used to that Android/Pixel stuff. The images found in [Pixel factory image](https://developer.android.com/about/versions/13/download) aren't the same as the images that can be downloaded with in Android Emulator in Android Studio?

Pixel phones came with a different Android version? What's the name of the ROM?

**Comment by warren-bank** [comment]
since I don't use it.. I'm not expert.. but my understanding of the emulator that comes with Android Studio is that is uses the qemu emulator and the AVD (android virtual device) images that it downloads directly from google are very much like a factory image.. in that's a zip file containing individual images for each partition.

as to which version.. or how old the images are.. I'm not sure.. does the AVD manager provide details about each image? ..it's not in front of me at the moment.

**Comment by mcastillof** [comment]
It booted now (x86_64 image)

![image](https://user-images.githubusercontent.com/6936113/232160203-1b0df97f-2118-431c-9586-81e10d47722f.png)

AVD manager only seems to say that it is an API 33:

```
Properties
avd.ini.displayname              Pixel 6 Pro API 33 2
avd.ini.encoding                 UTF-8
AvdId                            Pixel_6_Pro_API_33_2
disk.dataPartition.size          2G
fastboot.chosenSnapshotFile
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     2
hw.device.hash2                  MD5:a8abfd3536f3d35e4ba2041a7b99f40e
hw.device.manufacturer           Google
hw.device.name                   pixel_6_pro
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   560
hw.lcd.height                    3120
hw.lcd.width                     1440
hw.mainKeys                      no
hw.ramSize                       1536
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         33
image.sysdir.1                   system-images/android-33/google_apis/x86_64/
PlayStore.enabled                false
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google APIs
tag.id                           google_apis
vm.heapSize                      384
```

**Comment by mcastillof** [comment]
In the followin image, I downloaded Tiramisu (number 1 red), It showed me the url of the download, but I can't get access to it now,
If I try to download the number 2 red, it show this link 
https://dl.google.com/android/repository/sys-img/google_apis/x86_64-UpsideDownCake_r03.zip

![image](https://user-images.githubusercontent.com/6936113/232160982-f52a1264-9dfb-46ac-9543-829f667fef2f.png)

**Comment by warren-bank** [comment]
hmm.. I googled the build number.. but it didn't pull anything up.

going by the date of the last security update.. it should be pretty recent.

what happens when you run the last stable release of your app (that users are seeing this issue)?

**Comment by mcastillof** [comment]
Your fix seems to work fine, as I don't see that it crashes. I will try now without your fix.

**Comment by warren-bank** [comment]
the response for the URL of that system image includes the header:
```text
last-modified: Wed, 12 Apr 2023 16:15:00 GMT
```
..but that can't be right

**Comment by warren-bank** [comment]
pins and needles.. :smiley:

**Comment by mcastillof** [comment]
I couldn't reproduce the problem with the old code.

A new problem arises in FakeTraveler when using Android 13, 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cl.coders.faketraveler, PID: 11990
    java.lang.IllegalArgumentException: cl.coders.faketraveler: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
        at cl.coders.faketraveler.MainActivity.setAlarm(MainActivity.java:318)
        at cl.coders.faketraveler.MainActivity.applyLocation(MainActivity.java:270)
        at cl.coders.faketraveler.MainActivity$1.onClick(MainActivity.java:81)
        at android.view.View.performClick(View.java:7506)
        at android.view.View.performClickInternal(View.java:7483)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:29334)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/EGL_emulation: app_time_stats: avg=75.43ms min=4.31ms max=727.74ms count=13
I/Process: Sending signal. PID: 11990 SIG: 9

```

which is solved by changing this [line](https://github.com/mcastillof/FakeTraveler/blob/0b94df1463f979bfea558235eb8c3c3df4b29225/app/src/main/java/cl/coders/faketraveler/MainActivity.java#L318) to 

        pendingIntent = PendingIntent.getBroadcast(context, SCHEDULE_REQUEST_CODE, serviceIntent, PendingIntent.FLAG_CANCEL_CURRENT | PendingIntent.FLAG_IMMUTABLE);


I believe that your code already address this exception.

**Comment by warren-bank** [comment]
Yeah.. there was an issue about that (missing PendingIntent flag) error in one of my apps a few months ago.. and I pushed an update across all of them at the same time. Easy enough to fix.. just annoying how every new version of Android breaks user space and requires updates to keep existing functionality working.. big pet peave.

Anyway, as you said.. shame that the emulator wasn't any help. I mean.. this fix will definitely prevent the fatal error and "fix" this issue. My question is whether it's actually fixing initialization of the provider.. or simply catching the exception and allowing the app to ignore that it failed.

**Comment by mcastillof** [comment]
> Yeah.. there was an issue about that (missing PendingIntent flag) error in one of my apps a few months ago.. and I pushed an update across all of them at the same time. Easy enough to fix.. just annoying how every new version of Android breaks user space and requires updates to keep existing functionality working.. big pet peeve.

I think the same.

> Anyway, as you said.. shame that the emulator wasn't any help. But, huge thanks for bothering to test it! Would've been really nice to run this error through the debugger and be able to determine whether this workaround is actually fixing initialization of the provider.. or simply catching the exception and allowing the app to ignore that it failed.

We had to give it a try to the emulator.


Have a good day/night @warren-bank warren-bank :)

**Comment by mcastillof** [comment]
If somebody is still having this issue with FakeTraveler v1.9.1, which was released a few days ago in F-Droid, then please try if [this APK](https://c.coders.cl/s/8WfcoxB3MLBcKLa) is working for you and report it here.

**Comment by TimoGoetze** [comment]
Tried the one from F-Droid. First just did not work. Then Crashed again. I cannot try from coders.cl. 

``
type: crash
osVersion: google/oriole/oriole:13/TQ2A.230405.003.E1/2023041100:user/release-keys
package: cl.coders.faketraveler:9
process: cl.coders.faketraveler
processUptime: 4501 + 192 ms

java.lang.IllegalStateException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3029)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:2169)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2131)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2106)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2080)
	at cl.coders.faketraveler.MockLocationProvider.<init>(MockLocationProvider.java:28)
	at cl.coders.faketraveler.MainActivity.applyLocation(MainActivity.java:257)
	at cl.coders.faketraveler.MainActivity$1.onClick(MainActivity.java:81)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29357)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:200)
	at com.android.server.location.LocationManagerService.addLocationProviderManager(LocationManagerService.java:350)
	at com.android.server.location.LocationManagerService.getOrAddLocationProviderManager(LocationManagerService.java:342)
	at com.android.server.location.LocationManagerService.addTestProvider(LocationManagerService.java:1319)

**Comment by TimoGoetze** [comment]
pixel 6. latest updates.

**Comment by mcastillof** [comment]
Hello @TimoGoetze 

> Tried the one from F-Droid. First just did not work. Then Crashed again. I cannot try from coders.cl.

Did you experienced any problem with the download of the APK from c.coders.cl server?

I test the download and it worked without any problem. if you prefer I can upload the test APK here in Github.

**Comment by mcastillof** [comment]
@TimoGoetze I have pushed [this](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12922) beta release to F-Droid. It should be available soon in F-Droid's app. As this is a beta release, you will have to manually install it from the versions dropdown.

If you don't want to wait, you can download an unsigned apk built automatically by GitLab CI at the bottom of the [Merge Request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12922).

**Comment by UnlimitedCookies** [comment]
@mcastillof It seems the build failed at F-Droid.
Does this version also fix the missing FLAG_IMMUTABLE vor FLAG_MUTABLE for the PendingIntent ? (https://paste.crdroid.net/V6KHeN)

**Comment by warren-bank** [comment]
@UnlimitedCookies 
the [`FLAG_IMMUTABLE`](https://developer.android.com/reference/android/app/PendingIntent#FLAG_IMMUTABLE) flag is included in [`master`](https://github.com/mcastillof/FakeTraveler/blob/master/app/src/main/java/cl/coders/faketraveler/MainActivity.java#L318), but not in the most recent tag: [`v1.9.1`](https://github.com/mcastillof/FakeTraveler/blob/v1.9.1/app/src/main/java/cl/coders/faketraveler/MainActivity.java#L318)

@mcastillof
fwiw, although it probably isn't necessary, I like to make the inclusion of this flag conditional.. for example:
```java
serviceIntent = new Intent(context, ApplyMockBroadcastReceiver.class);

int flags = PendingIntent.FLAG_CANCEL_CURRENT;
if (Build.VERSION.SDK_INT >= 23)
  flags |= PendingIntent.FLAG_IMMUTABLE;

pendingIntent = PendingIntent.getBroadcast(context, SCHEDULE_REQUEST_CODE, serviceIntent, flags);
```

**Comment by mnalis** [comment]
> @TimoGoetze I have pushed [this](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12922) beta release to F-Droid. It should be available soon in F-Droid's app. As this is a beta release, you will have to manually install it from the versions dropdown.

As noted, unfortunately F-droid build of `v1.9.2-beta` seemed to [fail](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12922#note_1358604002), and thus it is not available at f-droid at all.

> If you don't want to wait, you can download an unsigned apk built automatically by GitLab CI at the bottom of the [Merge Request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12922).

Unfortunately, that `.apk` no longer seem available. I guess it is only kept for some short period of time.
Also, I was hoping to find pre-release APK on this Github repo, but no such luck.

I've ended up forking and [having GitHub compile it for me](https://github.com/mcastillof/FakeTraveler/compare/master...mnalis:FakeTraveler:master). It wasn't easy as usual, though, as `Android CI` GitHub workflow was failing. I've managed to make it work (by updating workflow, using not-recommended workaround of setting  [targetSdkVersion back to 30](https://stackoverflow.com/a/70573183/2600099)   and disabling lint.)

Luckily, the resulting `.apk` worked! (although, for Google Play release, the [real culprit](https://stackoverflow.com/a/68648841/2600099) of that compilation error should be found and fixed).

> Please, test the app and come back with feedback.

I've tested the latest master 1878d70baf6792c507283176cc5aa39c3620b843 on Android 13 (Samsung Galaxy S23+) and it no longer crashes there and works just fine! (if others want to try too, [the `.apk` built by GitHub](https://github.com/mnalis/FakeTraveler/actions/runs/7596431632)) should be available for next 90 days.

Can we have an release of `1.9.2` please, so regular f-droid.org users can benefit too?

**Comment by mcastillof** [comment]
Sorry I haven't had the time to take care of FakeTraveler. I will work on the project this days.

**Comment by ThexXTURBOXx** [comment]
Hello everyone! I have been added as a maintainer to this repo today. I will make sure that a published build of the current master is published as 1.9.2 to F-Droid soon!
After that, #74 will be merged (maybe alongside #75) in order to update most parts of the app to the currently newest standards.
This will then be release 2.0.0, which will also come with an increase of the min SDK version.
At least, these are my current plans - please let me know whenever you have concerns or questions! :)
